		--CARA MEMBUAT TABEL SENDIRI
CREATE TABLE iful (
	NIM INTEGER PRIMARY KEY,
	NamaDepan VARCHAR(10),
	NamaBelakang VARCHAR(10),
	NomorHP VARCHAR(14)
)


--CARA INPUT DATA
INSERT INTO iful(NIM,NamaDepan,NamaBelakang,NomorHP)
VALUES(051 ,'Saiful' ,'Andika' , 082241617784)

--CARA MELIHAT DATA YANG SUDAH DIINPUTKAN
SELECT * FROM iful 

--TUGAS INSERTKAN NAMA TEMAN KALIAN

